export const initialRouteState = {
  departure_id: null,
  departure_train_name: null,
  departure_from_city_name: null,
  departure_to_city_name: null,
  departure_from_datetime: null,
  departure_from_railway_station_name: null,
  departure_to_datetime: null,
  departure_to_railway_station_name: null,
  departure_duration: null,
  arrival_id: null,
  arrival_train_name: null,
  arrival_from_city_name: null,
  arrival_to_city_name: null,
  arrival_from_datetime: null,
  arrival_from_railway_station_name: null,
  arrival_to_datetime: null,
  arrival_to_railway_station_name: null,
  arrival_duration: null,
};